PDP-1017: Change pdp-distilbert-squad base image
pureinsights/pdp-distilbert-squad pull request #16
Opened 2023-02-08 23:04 UTC by dutsuwak

* Updated default image to nvidia/cuda:11.8.0-base-ubuntu22.04
* Updated installation of Python dependency as base image does not have it
* Added new optional parameters to payload to allow truncation and padding (both enabled by default)

[PDP-1017] [AUT-125]

2023-02-09 15:08 UTC, ricardo-leon-pureinsights submitted a review, later dismissed
This looks good. We have tested this on Autodesk's cluster and it works like a charm.

2023-02-09 18:48 UTC, julean-pi requested changes

2023-02-09 18:48 UTC, julean-pi commented on README.md
> +Optional parameters for the Paylod.
Payload

2023-02-09 18:48 UTC, julean-pi commented on README.md
> +* `"truncation"` : Truncates to the max lenght of the model. Defaults to `True`.
length

2023-02-09 18:48 UTC, julean-pi commented on README.md
> +* `"padding"` : Adds padding to comply with the min lenght of the model. Defaults to `True`.
length

2023-02-10 14:57 UTC, julean-pi approved these changes

2023-02-10 14:57 UTC, merged